---
 - hosts: all
   become: true
   become_user: root
   gather_facts: false
    

   tasks: 
     - include_role:
         name: adduser and  establish ssh
         tasks_from: add_user.yml
             
