---
 - hosts: all
   become: true
   become_user: root
   vars_files:
     - tomcat-vars.yml

   tasks:

#     - name: install java
#       yum:
#         name: java
#         state: latest
         
#     - alternatives: 
#         name: java
#         link: /usr/bin/java
#         path: $JAVA_HOME

     - debug: var=tomcat_url
       

#     - name: download tomcat server packages 
#       get_url:
#         url: "{{ tomcat_url }}"
#         dest: /usr/local

     - debug: var=tomcat_package   

#     - name: extract tomcat package 
#       unarchive: 
#          src: /usr/local/apache-tomcat-{{req_tomcat_version}}.tar.gz 
#          dest: /usr/local/
#          remote_src: yes

#     - name: start tomcat service
#       shell: nohup /usr/local/apache-tomcat-{{req_tomcat_version}}/bin/startup.sh

     - name: template file to replace server.xml  on remote host
       template: 
         src: server.xml.j2
         dest: /usr/local/apache-tomcat-{{req_tomcat_version}}/conf/server.xml

     - name: add lines in tomcat-users.xml
       lineinfile:
         path: /usr/local/apache-tomcat-{{req_tomcat_version}}/conf/tomcat-users.xml
         line: <role rolename="manager-gui" /> 
         create: yes
