---
 - name: add a new user
   user:
     name={{username}}
     password={{ devops_password }}
   tags: 
     - ssh

 - name: Add devops user to sudoers
   copy:
        dest: "/etc/sudoers.d/{{username}}"
        content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL" 
   tags:
     - ssh
 
                
 - name: Deploy ssh key
   authorized_key: user={{username}}
                   key="{{ lookup('file', 'id_rsa.pub') }}"
                   state=present
   tags:
     - ssh

- name: fetch all public ssh keys
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys
  tags: 
     - ssh
     
- name: check keys 
  debug: msg="{{ ssh_keys.stdout }}"   
  tags: 
    - ssh
    
- name: deploy keys on all servers
  authorized_key: user=root key="{{ item[0] }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
    - "{{ ssh_keys.stdout }}"
    - "{{groups['controllers']}}"
  tags:
    - ssh
   
 
 - name: disable  password authentication  and enable PubkeyAuthentication 
   lineinfile:
     dest=/etc/ssh/sshd_config
     regexp='^PasswordAuthentication'
     line='PasswordAuthentication no'
     regexp='^PubkeyAuthentication '
     line='PubkeyAuthentication yes' 
     state=present
     backup=yes
   tags: 
     - ssh
     
          
 - name: disable root login
   lineinfile: 
     dest=/etc/ssh/sshd_config
     regex='^PermitRootLogin'
     line='PermitRootLogin no'
     state=present
     backup=yes 
   tags:
     - ssh
       
   notify:
      - restart ssh
