---
 - name: add a new user
   user:
     name={{username}}
     password={{ devops_password }}
   tags:
     - ssh   

 - name: Add devops user to sudoers
   copy:
        dest: "/etc/sudoers.d/{{username}}"
        content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL" 
   tags:
     -ssh
 
                
 - name: Deploy ssh key
   authorized_key: user={{username}}
                   key="{{ lookup('file', 'id_rsa.pub') }}"
                   state=present

    
 
  
   
   notify:
      - restart ssh
    
