---
 - name: add a new user
   user:
     name={{username}}
     password={{ devops_password }}

 - name: Add devops user to sudoers
   copy:
        dest: "/etc/sudoers.d/{{username}}"
        content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL" 

 
                
 - name: Deploy ssh key
   authorized_key: user={{username}}
                   key="{{ lookup('file', 'id_rsa.pub') }}"
                   state=present



 - name: disable  password authentication  and enable PubkeyAuthentication 
   lineinfile:
     dest=/etc/ssh/sshd_config
     regexp='^PasswordAuthentication'
     line='PasswordAuthentication no'
     regexp='^PubkeyAuthentication '
     line='PubkeyAuthentication yes' 
     state=present
     backup=yes
                       
 - name: disable root login
   lineinfile: 
     dest=/etc/ssh/sshd_config
     regex='^PermitRootLogin'
     line='PermitRootLogin no'
     state=present
     backup=yes 

       
   notify:
      - restart ssh
