---
# - name: add several users with group devops
#   ansible.builtin.user:
#     name={{ item }}
#     password={{ devops_password }}
#   loop: 
#     - devops1
#     - devops2
#     - devops3
#     - devops4
#   tags:
#     - ssh   

 - name: Add devops user to sudoers
   copy:
        dest: "/etc/sudoers.d/{{username}}"
        content: "{{ item }}  ALL=(ALL)  NOPASSWD: ALL" 
   tags:
     -ssh
 
                
 - name: Deploy ssh key
   authorized_key: user={{username}}
                   key="{{ lookup('file', 'id_rsa.pub') }}"
                   state=present
   tags:
     - ssh
  
   
   notify:
      - restart ssh
    
