---
 - name: add a group 
   group: 
     name: devops
     state: present

 - name: add a new user
   user:
     name="{{ item }}"
     group="devops"
   loop: 
     - devops1
     - devops2
     - devops3
     - devops4
     - devops5
     - devops6
    
