---
- name: Install ngnix and start service
  hosts: all
  become: true
  
  tasks:
  - name: Install ngnix
    yum:
      name: nginx
      state: latest
    tags:
      -nginx

  - name: Start the service
    service:
      name: nginx
      state: started
    tags:
      - nginx  
